name: CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment
        with:
          python-version: 3.9  # You can change this to the version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies (if you have a requirements.txt)

      - name: Run Unit Tests
        run: |
          python -m unittest test_file.py  # Replace 'test_file.py' with the name of your test script

  # Optional Deploy Stage (if needed)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy only happens after the build is successful
    if: success()  # Only proceed if the build and tests are successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment"
          # Add your deploy command here (e.g., use AWS CLI, Heroku CLI, etc.)
